import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Nav from "./(components)/Nav";
import { getServerSession } from "next-auth";
import SessionProvider from "./(components)/SessionProvider";

const lato = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata = {
  title: "TKT",
  description: "Generated by TKT - Event Tickets",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={lato.className}>
        <SessionProvider session={session}>
          <Nav />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
